import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms & Conditions | RallyPoint',
  description: 'Terms and conditions for using the RallyPoint civic engagement platform.',
}

export default function TermsPage() {
  return (
    <div className="max-w-[960px] mx-auto px-6 py-12">
      <div className="mb-8">
        <h1 className="text-4xl font-bold text-on-surface font-headline mb-4">Terms & Conditions</h1>
        <p className="text-on-surface-variant">Last updated: March 21, 2026</p>
      </div>

      <div className="prose prose-neutral max-w-none">
        {[
          { title: '1. Acceptance of Terms', content: 'By accessing and using RallyPoint ("the Platform"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by these terms, please do not use this service.' },
          { title: '2. Description of Service', content: 'RallyPoint is a civic engagement platform that provides information about local government initiatives, petitions, and civic issues. The Platform aggregates publicly available information and provides AI-powered summaries to make civic documents more accessible.' },
        ].map((section, i) => (
          <section key={i} className="mb-8">
            <h2 className="text-2xl font-semibold text-on-surface font-headline mb-4">{section.title}</h2>
            <p className="text-on-surface-variant mb-4">{section.content}</p>
          </section>
        ))}

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-on-surface font-headline mb-4">3. User Accounts</h2>
          <ul className="list-disc pl-6 text-on-surface-variant mb-4 space-y-2">
            <li>You must be at least 13 years old to use this service</li>
            <li>You are responsible for maintaining the confidentiality of your account</li>
            <li>You agree to provide accurate and complete information during registration</li>
            <li>You are responsible for all activities that occur under your account</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-on-surface font-headline mb-4">4. User Conduct</h2>
          <p className="text-on-surface-variant mb-4">You agree not to:</p>
          <ul className="list-disc pl-6 text-on-surface-variant mb-4 space-y-2">
            <li>Use the Platform for any illegal purpose</li>
            <li>Post harassing, abusive, or threatening content</li>
            <li>Impersonate any person or entity</li>
            <li>Attempt to gain unauthorized access to any part of the Platform</li>
            <li>Interfere with or disrupt the Platform or servers</li>
            <li>Use automated systems to access the Platform without permission</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-on-surface font-headline mb-4">5. Content and AI Summaries</h2>
          <p className="text-on-surface-variant mb-4">AI-generated summaries are provided to help make civic documents more accessible. These summaries:</p>
          <ul className="list-disc pl-6 text-on-surface-variant mb-4 space-y-2">
            <li>Are generated by artificial intelligence and may contain errors</li>
            <li>Are not legal advice or official interpretations</li>
            <li>Should be verified against original source documents</li>
            <li>May be updated or corrected without notice</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-on-surface font-headline mb-4">6. Intellectual Property</h2>
          <p className="text-on-surface-variant mb-4">
            The Platform and its original content, features, and functionality are owned by RallyPoint and are protected by international copyright, trademark, and other intellectual property laws.
          </p>
          <p className="text-on-surface-variant mb-4">
            Government documents and public information displayed on the Platform remain the property of their respective government entities.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-on-surface font-headline mb-4">7. Limitation of Liability</h2>
          <p className="text-on-surface-variant mb-4">
            RallyPoint shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use the service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-on-surface font-headline mb-4">8. Changes to Terms</h2>
          <p className="text-on-surface-variant mb-4">
            We reserve the right to modify these terms at any time. We will notify users of any material changes by posting the new terms on the Platform. Your continued use of the Platform after such changes constitutes your acceptance of the new terms.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold text-on-surface font-headline mb-4">9. Contact Information</h2>
          <p className="text-on-surface-variant mb-4">
            If you have any questions about these Terms & Conditions, please contact us at:
          </p>
          <div className="bg-surface-container-low p-4 rounded-2xl">
            <p className="text-on-surface-variant">Email: legal@rallypoint.app</p>
            <p className="text-on-surface-variant">Address: 123 Civic Center Dr</p>
          </div>
        </section>
      </div>
    </div>
  )
}
