/**
 * AI-related constants that can be safely imported in client components
 */

/**
 * Standard disclaimer for AI-generated summaries
 */
export const AI_SUMMARY_DISCLAIMER =
  'This summary was generated by AI to help make civic documents more accessible. It is not legal advice. Always refer to the official document for authoritative information.'
