import { prisma } from '../db/prisma'
import { summarizeCivicDocument } from './claude'
import type { AISummaryOutput } from '../validators/ai'

/**
 * Standard disclaimer for AI-generated summaries
 */
export const AI_SUMMARY_DISCLAIMER =
  'This summary was generated by AI to help make civic documents more accessible. It is not legal advice. Always refer to the official document for authoritative information.'

/**
 * Process a summarization job for a source document
 *
 * @param sourceDocumentId - The ID of the source document to summarize
 * @returns The created AI summary
 *
 * TODO: Move to job queue (BullMQ or similar) for production
 * For MVP, this runs synchronously when called
 */
export async function processSummarizationJob(sourceDocumentId: string) {
  try {
    // 1. Load source document from database
    const sourceDocument = await prisma.sourceDocument.findUnique({
      where: { id: sourceDocumentId },
      include: {
        civicItem: true, // Include parent civic item for metadata
      },
    })

    if (!sourceDocument) {
      throw new Error(`Source document ${sourceDocumentId} not found`)
    }

    if (!sourceDocument.fullText) {
      throw new Error(`Source document ${sourceDocumentId} has no text content`)
    }

    // 2. Update status to processing
    await prisma.sourceDocument.update({
      where: { id: sourceDocumentId },
      data: { processingStatus: 'PROCESSING' },
    })

    // 3. Call Claude AI to generate summary
    const metadata = {
      title: sourceDocument.civicItem.title,
      type: sourceDocument.civicItem.type,
      jurisdiction: sourceDocument.civicItem.jurisdictionTags[0] || undefined,
    }

    console.log(`Starting summarization for document ${sourceDocumentId}...`)
    const aiOutput: AISummaryOutput = await summarizeCivicDocument(
      sourceDocument.fullText,
      metadata
    )

    // 4. Store AI summary in database
    const aiSummary = await prisma.aISummary.create({
      data: {
        civicItemId: sourceDocument.civicItemId,
        sourceDocumentId: sourceDocument.id,
        plainSummary: aiOutput.plainSummary,
        whoAffected: aiOutput.whoAffected,
        whatChanges: aiOutput.whatChanges,
        whyItMatters: aiOutput.whyItMatters,
        argumentsFor: aiOutput.argumentsFor,
        argumentsAgainst: aiOutput.argumentsAgainst,
        importantDates: aiOutput.importantDates,
        nextActions: aiOutput.nextActions,
        categories: aiOutput.categories,
        affectedJurisdictions: aiOutput.affectedJurisdictions,
        generatedAt: new Date(),
      },
    })

    // 5. Update source document status to completed
    await prisma.sourceDocument.update({
      where: { id: sourceDocumentId },
      data: {
        processingStatus: 'COMPLETED',
        processedAt: new Date(),
      },
    })

    // 6. Update civic item with extracted categories and jurisdictions
    await prisma.civicItem.update({
      where: { id: sourceDocument.civicItemId },
      data: {
        categories: aiOutput.categories,
        jurisdictionTags: aiOutput.affectedJurisdictions,
      },
    })

    console.log(
      `Successfully completed summarization for document ${sourceDocumentId}`
    )

    return aiSummary
  } catch (error: any) {
    console.error(`Summarization job failed for ${sourceDocumentId}:`, error)

    // Update status to failed
    await prisma.sourceDocument.update({
      where: { id: sourceDocumentId },
      data: {
        processingStatus: 'FAILED',
        processedAt: new Date(),
      },
    })

    throw new Error(`Summarization failed: ${error.message || 'Unknown error'}`)
  }
}

/**
 * Batch process multiple source documents
 *
 * @param sourceDocumentIds - Array of source document IDs
 * @returns Array of results with successes and failures
 *
 * TODO: In production, queue these as separate jobs instead of running synchronously
 */
export async function batchProcessSummarizations(sourceDocumentIds: string[]) {
  const results = {
    successful: [] as string[],
    failed: [] as { id: string; error: string }[],
  }

  for (const docId of sourceDocumentIds) {
    try {
      await processSummarizationJob(docId)
      results.successful.push(docId)
    } catch (error: any) {
      results.failed.push({
        id: docId,
        error: error.message || 'Unknown error',
      })
    }
  }

  return results
}

/**
 * Regenerate summary for a civic item
 * Useful if prompts are updated and you want to re-summarize
 *
 * @param civicItemId - The civic item ID
 * @returns The new AI summary
 */
export async function regenerateSummary(civicItemId: string) {
  // Find the source document for this civic item
  const sourceDocument = await prisma.sourceDocument.findFirst({
    where: { civicItemId },
    orderBy: { uploadedAt: 'desc' }, // Use most recent if multiple
  })

  if (!sourceDocument) {
    throw new Error(`No source document found for civic item ${civicItemId}`)
  }

  // Archive old summary if exists
  const existingSummary = await prisma.aISummary.findFirst({
    where: { civicItemId },
  })

  if (existingSummary) {
    // In production, you might want to keep old summaries with a version field
    // For now, we'll just delete and replace
    await prisma.aISummary.delete({
      where: { id: existingSummary.id },
    })
  }

  // Generate new summary
  return processSummarizationJob(sourceDocument.id)
}
